############# English navigation ##############

# main menu
[[main]]
name = "Portfolio"
url = "/portfolio"
weight = 1

[[main]]
name = "Ethical Hacking Blogs"
url = "/blog"
weight = 2


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
