name: Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - main # Sesuaikan dengan branch utama repo kamu

  workflow_dispatch: # Memungkinkan menjalankan workflow secara manual di GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Build Hugo
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: main # Branch tempat hasil build akan disimpan
